
openapi: 3.0.3 # Versão da especificação

info: # Inicia uma seção com informações gerais sobre a API
  title: Mini API de Produtos
  version: 1.0.0
  description: API para demonstrar testes de contrato.

servers:
  - url: http://localhost:3000

paths: # Definição dos endpoints
  /produtos/{id}:
    get:
      summary: Buscar produto por ID
      description: Retorna um produto cadastrado.

      parameters: # Quais parâmetros podem ou devem ser enviados para a operação
        - name: id
          in: path # Faz parte da URL
          required: true # Parâmetro obrigatório
          schema: # Inicia a definição das características e restrições do parâmetro
            type: integer

      responses: #Respostas possíveis da operação
        '200':
          description: Produto encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produto'

        '404':
          description: Produto não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'

components: # Início da seção de componentes reutilizáveis
  schemas:
    Produto:
      type: object

      required:
        - id
        - nome
        - preco
        - disponivel

      properties: # Propriedades que podem aparecer no objeto produto
        id:
          type: integer
          example: 10

        nome:
          type: string
          example: Notebook

        preco:
          type: number
          minimum: 0
          example: 3500.00

        disponivel:
          type: boolean
          example: true

    Erro:
      type: object

      required:
        - mensagem

      properties:
        mensagem:
          type: string
          example: Produto não encontrado