const scenarios = [
  {id:'A',title:'Produto após uma atualização',description:'Uma alteração recente foi publicada nesta resposta.',json:{id:10,nome:'Notebook',preco:'3500.00',disponivel:true},keys:['preco'],issues:['preco é string; o contrato exige number.'],fix:'Remova as aspas do preço.',corrected:{id:10,nome:'Notebook',preco:3500,disponivel:true}},
  {id:'B',title:'Preço e disponibilidade',description:'Confira os tipos e os limites definidos no contrato.',json:{id:20,nome:'Mouse',preco:-89.9,disponivel:'false'},keys:['preco','disponivel'],issues:['preco é menor que minimum: 0.','disponivel é string; o contrato exige boolean.'],fix:'Use um preço maior ou igual a zero e o booleano false, sem aspas.',corrected:{id:20,nome:'Mouse',preco:89.9,disponivel:false}},
  {id:'C',title:'Nova informação de estoque',description:'Uma propriedade nova aparece junto aos campos conhecidos.',json:{id:30,nome:'Teclado',preco:150,disponivel:true,estoque:12},keys:[],issues:[],fix:'',corrected:null},
  {id:'D',title:'Dados incompletos',description:'Há um campo ausente e um texto que merece atenção.',json:{id:40,nome:'',preco:250},keys:['nome','disponivel'],issues:['disponivel é obrigatório e está ausente.','nome está vazio e viola minLength: 1.'],fix:'Preencha nome com texto não vazio e inclua disponivel como booleano.',corrected:{id:40,nome:'Produto',preco:250,disponivel:true}}
];
const contractYaml=`Produto:\n  type: object\n  required:\n    - id\n    - nome\n    - preco\n    - disponivel\n  properties:\n    id:\n      type: integer\n    nome:\n      type: string\n      minLength: 1\n    preco:\n      type: number\n      minimum: 0\n    disponivel:\n      type: boolean`;
const app=document.querySelector('#app'),dialog=document.querySelector('#contract-dialog');
let state={screen:'home',index:0,answers:scenarios.map(()=>({decision:'',fields:[],proposal:''})),revealed:false};
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function setScreen(screen){state.screen=screen;render();window.scrollTo({top:0,behavior:'smooth'});}
function highlightedJson(item){return codeJson(item)}
function codeJson(obj){return escapeHtml(JSON.stringify(obj,null,2)).replace(/"([^"]+)":/g,'<span class="key">"$1"</span>:').replace(/: "([^"]*)"/g,': <span class="str">"$1"</span>').replace(/: (-?\d+(?:\.\d+)?)/g,': <span class="num">$1</span>').replace(/: (true|false)/g,': <span class="bool">$1</span>')}
function choiceFields(item,a){return item.keys.length?`<div class="question">Quais campos apresentam problemas?</div><div class="field-grid">${item.keys.map(k=>`<label class="field-option"><input type="checkbox" data-field="${k}" ${a.fields.includes(k)?'checked':''}><span><code>${k}</code>${k==='nome'?' — texto vazio':k==='disponivel'?' — ausente ou tipo incorreto':k==='preco'?' — valor ou tipo incorreto':''}</span></label>`).join('')}</div>`:''}
function renderScenario(){const i=state.index,item=scenarios[i],a=state.answers[i];return `<div class="section-head"><div><p class="eyebrow">ANÁLISE DE RESPOSTA</p><h1>Investigue o cenário</h1></div><button class="btn small-btn secondary" data-contract>Consultar contrato</button></div><div class="progress-meta"><span>Cenário ${i+1} de ${scenarios.length}</span><span>${Math.round((i/scenarios.length)*100)}% concluído</span></div><div class="progress-track"><div class="progress-fill" style="width:${((i+1)/scenarios.length)*100}%"></div></div><section class="card"><div class="scenario-title"><span class="scenario-letter">${item.id}</span><div><h2>${escapeHtml(item.title)}</h2><p>${escapeHtml(item.description)}</p></div></div><pre class="code" aria-label="Resposta JSON do cenário ${item.id}"><code>${highlightedJson(item)}</code></pre><p class="question">Esta resposta respeita o contrato?</p><div class="choice-grid"><label class="choice"><input type="radio" name="decision" value="conforme" ${a.decision==='conforme'?'checked':''}> Está em conformidade</label><label class="choice"><input type="radio" name="decision" value="viola" ${a.decision==='viola'?'checked':''}> Viola o contrato</label></div>${a.decision==='viola'?`${choiceFields(item,a)}<label class="proposal-label" for="proposal">Proposta de correção <span>(opcional)</span></label><textarea id="proposal" class="text-input" placeholder="Como você corrigiria esta resposta?">${escapeHtml(a.proposal)}</textarea>`:''}</section><div class="nav-row"><button class="btn secondary" data-prev ${i===0?'disabled':''}>← Anterior</button><div class="nav-right"><button class="btn secondary" data-review>Revisar decisões</button><button class="btn primary" data-next>${i===3?'Revisar investigação':'Próximo cenário →'}</button></div></div>`}
function answerLine(i){const a=state.answers[i],item=scenarios[i];return `<div class="answer-summary"><p><strong>Decisão:</strong> ${a.decision==='conforme'?'Está em conformidade':a.decision==='viola'?'Viola o contrato':'Sem resposta'}</p>${a.decision==='viola'?`<p><strong>Campos selecionados:</strong> ${a.fields.length?a.fields.map(escapeHtml).join(', '):'nenhum'}</p><p><strong>Correção proposta:</strong> ${escapeHtml(a.proposal||'não registrada')}</p>`:''}</div>`}
function analysis(i){const item=scenarios[i],valid=item.issues.length===0,problems=valid?'O cenário está em conformidade. A propriedade adicional estoque é permitida porque o schema não define additionalProperties: false.':item.issues.map(x=>`<li>${escapeHtml(x)}</li>`).join('');return `<div class="analysis"><strong>Análise do contrato</strong>${valid?`<p>O cenário C está em conformidade com o schema apresentado. O campo <code>estoque</code> é permitido porque o contrato não define <code>additionalProperties: false</code>.</p>`:`<ul>${problems}</ul><p><strong>Exemplo corrigido:</strong></p><pre class="code"><code>${codeJson(item.corrected)}</code></pre>`}</div>`}
function renderReview(){return `<div class="section-head"><div><p class="eyebrow">CONVERSA DE EQUIPE</p><h1>Revisão da investigação</h1></div><button class="btn small-btn secondary" data-contract>Consultar contrato</button></div><p class="muted">Reúnam as decisões do grupo. A análise fica oculta até vocês escolherem revelar.</p>${scenarios.map((s,i)=>`<section class="card review-item"><h3><span class="scenario-letter">${s.id}</span>${escapeHtml(s.title)} <span class="tag ${!state.answers[i].decision?'pending':!state.revealed?'yes':((state.answers[i].decision==='viola')===(s.issues.length>0)?'yes':'no')}">${!state.answers[i].decision?'sem resposta':!state.revealed?'respondido':((state.answers[i].decision==='viola')===(s.issues.length>0)?'correta':'incorreta')}</span></h3>${answerLine(i)}${state.revealed?analysis(i):`<button class="btn small-btn secondary" data-edit="${i}">Editar resposta</button>`}</section>`).join('')}${state.revealed?`<div class="completed"><strong>Investigação concluída!</strong><br>Os testes de contrato ajudam a identificar incompatibilidades entre as respostas de uma API e as regras definidas no contrato.<p class="small">A conformidade com o schema não garante automaticamente compatibilidade com todos os consumidores da API.</p></div><div class="button-row" style="margin-top:20px"><button class="btn primary" data-reset>Reiniciar investigação</button></div>`:`<div class="button-row"><button class="btn primary" data-reveal>Revelar análise dos contratos</button></div>`}`}
function renderTeacher(){const i=state.index,s=scenarios[i];return `<div class="teacher-top"><div><p class="eyebrow">MODO DE APRESENTAÇÃO</p><h1>Detetives de Contratos</h1></div><button class="btn small-btn secondary" data-home>Sair da apresentação</button></div><div class="teacher-nav"><button class="btn small-btn secondary" data-prev ${i===0?'disabled':''}>← Anterior</button><span class="muted">${s.id} · Cenário ${i+1} de 4</span><button class="btn small-btn secondary" data-next>${i===3?'Contrato':'Próximo →'}</button></div><section class="card"><div class="scenario-title"><span class="scenario-letter">${s.id}</span><div><h2>${escapeHtml(s.title)}</h2><p>${escapeHtml(s.description)}</p></div></div><pre class="code teacher-code"><code>${codeJson(s.json)}</code></pre><div class="button-row" style="justify-content:flex-start;margin-top:18px"><button class="btn secondary" data-toggle-analysis>${state.revealed?'Ocultar análise':'Revelar análise e correção'}</button><button class="btn secondary" data-teacher-contract>Exibir contrato</button></div>${state.revealed?`<div class="analysis teacher-analysis">${analysis(i)}</div>`:''}</section>`}
function render(){app.innerHTML=state.screen==='home'?`<section class="hero"><p class="eyebrow">DINÂMICA INTERATIVA · OPENAPI</p><h1>Detetives de <em>Contratos</em></h1><p class="subtitle">Encontre os bugs antes do deploy!</p><p class="lead">Uma nova versão da API de produtos está prestes a entrar em produção. Sua missão é investigar quatro respostas da API, identificar possíveis violações do contrato OpenAPI e propor correções antes da liberação.</p><ol class="steps"><li><b>01</b> Formem grupos de 3 a 5 participantes</li><li><b>02</b> Analisem o contrato OpenAPI</li><li><b>03</b> Investiguem os quatro cenários</li><li><b>04</b> Identifiquem incompatibilidades</li><li><b>05</b> Discutam e proponham correções em equipe</li></ol><div class="button-row"><button class="btn primary" data-start>Iniciar investigação</button><button class="btn secondary" data-teacher>Modo de apresentação</button></div><p class="note">10 a 15 minutos · sem cadastro · progresso salvo neste dispositivo</p></section>`:state.screen==='contract'?`<p class="eyebrow">REFERÊNCIA DA INVESTIGAÇÃO</p><h1>Contrato OpenAPI</h1><p class="muted">Esta referência continua disponível em todos os cenários.</p><pre class="code yaml"><code>${escapeHtml(contractYaml)}</code></pre><ul class="rules"><li><code>id</code>: número inteiro obrigatório.</li><li><code>nome</code>: texto obrigatório, com pelo menos um caractere.</li><li><code>preco</code>: número obrigatório, maior ou igual a zero.</li><li><code>disponivel</code>: booleano obrigatório (<code>true</code> ou <code>false</code>).</li></ul><p class="muted small">Propriedades adicionais são permitidas porque o schema não declara <code>additionalProperties: false</code>.</p><div class="button-row"><button class="btn primary" data-start>Começar investigação</button><button class="btn secondary" data-home>Voltar ao início</button></div>`:state.screen==='scenario'?renderScenario():state.screen==='review'?renderReview():renderTeacher();}
function save(){try{localStorage.setItem('detetives-contratos-progress',JSON.stringify({answers:state.answers,index:state.index,screen:state.screen,revealed:state.revealed}));}catch{}}
function load(){try{const x=JSON.parse(localStorage.getItem('detetives-contratos-progress'));if(x&&Array.isArray(x.answers)&&x.answers.length===4){state.answers=x.answers.map(a=>({decision:a.decision||'',fields:Array.isArray(a.fields)?a.fields:[],proposal:a.proposal||''}));state.index=Math.max(0,Math.min(3,x.index||0));state.screen=x.screen==='scenario'||x.screen==='review'?x.screen:'home';state.revealed=!!x.revealed;}}catch{}}
app.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-contract')||b.hasAttribute('data-teacher-contract')){dialog.showModal();return}if(b.hasAttribute('data-start')){state.screen='scenario';state.index=0;render();save();return}if(b.hasAttribute('data-home')){state.screen='home';state.revealed=false;render();return}if(b.hasAttribute('data-teacher')){state.screen='teacher';state.index=0;state.revealed=false;render();return}if(b.hasAttribute('data-prev')){state.index=Math.max(0,state.index-1);render();save();return}if(b.hasAttribute('data-next')){if(state.screen==='teacher'&&state.index===3){dialog.showModal();return}if(state.screen==='scenario'&&state.index===3){state.screen='review'}else state.index=Math.min(3,state.index+1);render();save();return}if(b.hasAttribute('data-review')){state.screen='review';render();save();return}if(b.hasAttribute('data-reveal')){state.revealed=true;render();save();return}if(b.hasAttribute('data-edit')){state.index=Number(b.dataset.edit);state.screen='scenario';render();return}if(b.hasAttribute('data-reset')){state.answers=scenarios.map(()=>({decision:'',fields:[],proposal:''}));state.index=0;state.revealed=false;state.screen='home';save();render();return}if(b.hasAttribute('data-toggle-analysis')){state.revealed=!state.revealed;render();return}});
app.addEventListener('change',e=>{if(e.target.name==='decision'){state.answers[state.index].decision=e.target.value;render();save()}if(e.target.matches('[data-field]')){const fields=state.answers[state.index].fields,k=e.target.dataset.field;state.answers[state.index].fields=e.target.checked?[...new Set([...fields,k])]:fields.filter(x=>x!==k);save()}});
app.addEventListener('input',e=>{if(e.target.id==='proposal'){state.answers[state.index].proposal=e.target.value;save()}});
dialog.addEventListener('click',e=>{if(e.target===dialog||e.target.closest('[data-close-dialog]'))dialog.close()});
load();render();
